name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'pyproject.toml'

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  tag:
    needs: ci
    permissions:
      contents: write
    uses: ./.github/workflows/tag.yml

  pypi-publish:
    needs: tag
    permissions:
      contents: read
      id-token: write
    environment: pypi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --all-extras

    - name: Build
      run: poetry build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.12.3

    - name: Recovery time for PyPi
      run: sleep 30

  publish-test:
    needs: pypi-publish
    uses: ./.github/workflows/publish-test.yml
